scylla_node: hostid: handle errors
If `hostid()` is called too early, it may fail as follows:
```
           requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.89.5', port=10000): Max retries exceeded with url: /storage_service/hostid/local (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa20680aa50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Just print the error and return None to indicate that the
hostid is unknown.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>